amdin : adeljck
uri : mongodb://localhost:27017/?direct=true
adminpwd : weiruyi123
database : makespace
ak : j9rRQY-AeDP55mLoOM3ygJUqZulDIEPcTvRS8rMd
sk : r8xjsrjdyX5qli9igXUWpUWAY5fZOIpgVjOaF5Vc
bucket : makespaceadel3
aliaccount : adeljck@1361001560617386.onaliyun.com
akid : LTAI4FwzzCWsS6yctiyMh9UZ
aks : mtOkOATI5gSu8xBGXs5gWGoBZS4vMV
alibucket : makespace
aliendpoint : oss-cn-shenzhen.aliyuncs.com