// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2020-05-16 00:47:51.852005 +0800 CST m=+0.072595129

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://www.hnit.edu.cn",
        "contact": {
            "name": "adeljck",
            "url": "http://adeljck.github.io",
            "email": "fuck@you.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/enterpriseapply": {
            "post": {
                "description": "企业入驻",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "企业入驻",
                "parameters": [
                    {
                        "description": "enterprise",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.Enterprise"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":200, \"msg\": \"success\" }",
                        "schema": {
                            "$ref": "#/definitions/serializer.Response"
                        }
                    },
                    "4001": {
                        "description": "code\":4001,\"data\":null,\"msg\":\"JSON类型不匹配\"}",
                        "schema": {
                            "$ref": "#/definitions/serializer.Response"
                        }
                    },
                    "4002": {
                        "description": "code\":4002,\"data\":null,\"msg\":\"参数错误\"}",
                        "schema": {
                            "$ref": "#/definitions/serializer.Response"
                        }
                    },
                    "4003": {
                        "description": "code\":4003,\"data\":null,\"msg\":\"Tag Error\"}",
                        "schema": {
                            "$ref": "#/definitions/serializer.Response"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "用户登陆",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "用户登陆",
                "parameters": [
                    {
                        "description": "user",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.UserLoginService"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\": 200,\"data\":{\"_id\":000000,\"token\":token,\"name\":adeljck},\"msg\": \"success\" }",
                        "schema": {
                            "$ref": "#/definitions/serializer.Response"
                        }
                    },
                    "4001": {
                        "description": "code\":4001,\"data\":null,\"msg\":\"JSON类型不匹配\"}",
                        "schema": {
                            "$ref": "#/definitions/serializer.Response"
                        }
                    },
                    "4002": {
                        "description": "code\":4002,\"data\":null,\"msg\":\"参数错误\"}",
                        "schema": {
                            "$ref": "#/definitions/serializer.Response"
                        }
                    },
                    "4003": {
                        "description": "code\":4003,\"data\":null,\"msg\":\"Tag Error\"}",
                        "schema": {
                            "$ref": "#/definitions/serializer.Response"
                        }
                    },
                    "4005": {
                        "description": "code\":4003,\"data\":null,\"msg\":\"账号或密码错误\"}",
                        "schema": {
                            "$ref": "#/definitions/serializer.Response"
                        }
                    },
                    "4006": {
                        "description": "code\":4003,\"data\":null,\"msg\":\"unauthrized account\"}",
                        "schema": {
                            "$ref": "#/definitions/serializer.Response"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "服务器状态检查",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "服务器状态检查",
                "responses": {
                    "200": {
                        "description": "{\"status\": 0,\"data\": null,\"msg\": \"Pong\" }",
                        "schema": {
                            "$ref": "#/definitions/serializer.Response"
                        }
                    }
                }
            }
        },
        "/project/add": {
            "post": {
                "description": "添加项目",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "添加项目",
                "parameters": [
                    {
                        "description": "project",
                        "name": "projects",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.ProjectAdd"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\": 200,\"data\":bull,\"msg\": \"success\" }",
                        "schema": {
                            "$ref": "#/definitions/serializer.Response"
                        }
                    },
                    "4001": {
                        "description": "code\":4001,\"data\":null,\"msg\":\"JSON类型不匹配\"}",
                        "schema": {
                            "$ref": "#/definitions/serializer.Response"
                        }
                    },
                    "4002": {
                        "description": "code\":4002,\"data\":null,\"msg\":\"参数错误\"}",
                        "schema": {
                            "$ref": "#/definitions/serializer.Response"
                        }
                    },
                    "4003": {
                        "description": "code\":4003,\"data\":null,\"msg\":\"Tag Error\"}",
                        "schema": {
                            "$ref": "#/definitions/serializer.Response"
                        }
                    }
                }
            }
        },
        "/project/list/{page}": {
            "get": {
                "description": "项目列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "项目列表",
                "parameters": [
                    {
                        "description": "project",
                        "name": "projects",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.Project"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\": 200,\"data\":{\"item\":[],total:int},\"msg\": \"success\" }",
                        "schema": {
                            "$ref": "#/definitions/serializer.Response"
                        }
                    }
                }
            }
        },
        "/registe": {
            "post": {
                "description": "用户注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "user",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\": 200,\"data\":null,\"msg\": \"success\" }",
                        "schema": {
                            "$ref": "#/definitions/serializer.Response"
                        }
                    },
                    "4001": {
                        "description": "code\":4001,\"data\":null,\"msg\":\"JSON类型不匹配\"}",
                        "schema": {
                            "$ref": "#/definitions/serializer.Response"
                        }
                    },
                    "4002": {
                        "description": "code\":4002,\"data\":null,\"msg\":\"参数错误\"}",
                        "schema": {
                            "$ref": "#/definitions/serializer.Response"
                        }
                    },
                    "4003": {
                        "description": "code\":4003,\"data\":null,\"msg\":\"Tag Error\"}",
                        "schema": {
                            "$ref": "#/definitions/serializer.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "serializer.Response": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object"
                },
                "msg": {
                    "type": "object"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "service.Enterprise": {
            "type": "object",
            "required": [
                "companycode",
                "date",
                "email",
                "industry",
                "info",
                "legal",
                "legalid",
                "name",
                "phone",
                "site"
            ],
            "properties": {
                "companycode": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "industry": {
                    "type": "string"
                },
                "info": {
                    "type": "string"
                },
                "legal": {
                    "type": "string"
                },
                "legalid": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "site": {
                    "type": "string"
                }
            }
        },
        "service.Project": {
            "type": "object",
            "properties": {
                "_id": {
                    "type": "string"
                },
                "creator": {
                    "type": "string"
                },
                "money": {
                    "type": "number"
                },
                "project_name": {
                    "type": "string"
                },
                "short_info": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "stop_time": {
                    "type": "string"
                }
            }
        },
        "service.ProjectAdd": {
            "type": "object",
            "required": [
                "attach",
                "contact",
                "creator",
                "info",
                "money",
                "project_name",
                "short_info",
                "start_time",
                "status",
                "stop_time"
            ],
            "properties": {
                "attach": {
                    "type": "string"
                },
                "contact": {
                    "type": "object",
                    "$ref": "#/definitions/service.contact"
                },
                "creator": {
                    "type": "string"
                },
                "info": {
                    "type": "string"
                },
                "money": {
                    "type": "number"
                },
                "project_name": {
                    "type": "string"
                },
                "short_info": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "stop_time": {
                    "type": "string"
                }
            }
        },
        "service.User": {
            "type": "object",
            "required": [
                "academy",
                "class",
                "date",
                "email",
                "major",
                "name",
                "password",
                "phone",
                "repassword",
                "sid"
            ],
            "properties": {
                "academy": {
                    "type": "string"
                },
                "class": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "major": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "repassword": {
                    "type": "string"
                },
                "sid": {
                    "type": "string"
                }
            }
        },
        "service.UserLoginService": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "service.contact": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "qq": {
                    "type": "string"
                },
                "wechat": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "127.0.0.1:3000",
	BasePath:    "/api/v1",
	Schemes:     []string{},
	Title:       "湖南工学院创客系统API",
	Description: "湖南工学院创客系统API介绍",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
