basePath: /api/v1
definitions:
  serializer.PureErrorResponse:
    properties:
      msg:
        type: object
      status:
        type: integer
    type: object
  serializer.Response:
    properties:
      data:
        type: object
      msg:
        type: object
      status:
        type: integer
    type: object
  service.Enterprise:
    properties:
      companycode:
        type: string
      date:
        type: string
      email:
        type: string
      industry:
        type: string
      info:
        type: string
      legal:
        type: string
      legalid:
        type: string
      name:
        type: string
      phone:
        type: string
      site:
        type: string
    required:
    - companycode
    - date
    - email
    - industry
    - info
    - legal
    - legalid
    - name
    - phone
    - site
    type: object
  service.GetProject:
    properties:
      id:
        type: string
    type: object
  service.ProjectAdd:
    properties:
      attach:
        type: string
      contact:
        $ref: '#/definitions/service.contact'
        type: object
      creator:
        type: string
      info:
        type: string
      money:
        type: number
      project_name:
        type: string
      short_info:
        type: string
      start_time:
        type: string
      status:
        type: integer
      stop_time:
        type: string
    required:
    - attach
    - contact
    - creator
    - info
    - money
    - project_name
    - short_info
    - start_time
    - status
    - stop_time
    type: object
  service.ProjectDelete:
    properties:
      id:
        type: string
    required:
    - id
    type: object
  service.User:
    properties:
      academy:
        type: string
      class:
        type: string
      date:
        type: string
      email:
        type: string
      major:
        type: string
      name:
        type: string
      password:
        type: string
      phone:
        type: string
      repassword:
        type: string
      sid:
        type: string
    required:
    - academy
    - class
    - date
    - email
    - major
    - name
    - password
    - phone
    - repassword
    - sid
    type: object
  service.UserChangePassword:
    properties:
      oldpassword:
        type: string
      password:
        type: string
      repassword:
        type: string
    required:
    - oldpassword
    - password
    - repassword
    type: object
  service.UserForget:
    properties:
      email:
        type: string
      phone:
        type: string
      sid:
        type: string
    required:
    - email
    - phone
    - sid
    type: object
  service.UserForgetChangePassword:
    properties:
      password:
        type: string
      repassword:
        type: string
    required:
    - password
    - repassword
    type: object
  service.UserLoginService:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  service.contact:
    properties:
      email:
        type: string
      phone:
        type: string
      qq:
        type: string
      wechat:
        type: string
    required:
    - email
    type: object
host: 127.0.0.1:3000
info:
  contact:
    email: fuck@you.com
    name: adeljck
    url: http://adeljck.github.io
  description: 湖南工学院创客系统API介绍
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://www.hnit.edu.cn
  title: 湖南工学院创客系统API
  version: "1.0"
paths:
  /academy:
    get:
      description: 学院列表
      produces:
      - application/json
      responses:
        "200":
          description: '{"status": 200,"data":{"item":[],total:int},"msg": "success"
            }'
          schema:
            $ref: '#/definitions/serializer.Response'
      summary: 学院列表
  /enterpriseapply:
    post:
      consumes:
      - application/json
      description: 企业入驻
      parameters:
      - description: enterprise
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/service.Enterprise'
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":200, "msg": "success" }'
          schema:
            $ref: '#/definitions/serializer.Response'
        "4001":
          description: code":4001,"data":null,"msg":"JSON类型不匹配"}
          schema:
            $ref: '#/definitions/serializer.Response'
        "4002":
          description: code":4002,"data":null,"msg":"参数错误"}
          schema:
            $ref: '#/definitions/serializer.Response'
        "4003":
          description: code":4003,"data":null,"msg":"Tag Error"}
          schema:
            $ref: '#/definitions/serializer.Response'
      summary: 企业入驻
  /forget:
    post:
      consumes:
      - application/json
      description: 忘记密码
      parameters:
      - description: user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/service.UserForget'
      produces:
      - application/json
      responses:
        "200":
          description: '{"status": 200,"data":{"_id":000000,"token":token,"name":adeljck},"msg":
            "success" }'
          schema:
            $ref: '#/definitions/serializer.Response'
        "4001":
          description: code":4001,"data":null,"msg":"JSON类型不匹配"}
          schema:
            $ref: '#/definitions/serializer.Response'
        "4002":
          description: code":4002,"data":null,"msg":"参数错误"}
          schema:
            $ref: '#/definitions/serializer.Response'
        "4003":
          description: code":4003,"data":null,"msg":"Tag Error"}
          schema:
            $ref: '#/definitions/serializer.Response'
        "4006":
          description: code":4003,"data":null,"msg":"unauthrized account"}
          schema:
            $ref: '#/definitions/serializer.Response'
      summary: 忘记密码
  /forget/changepassword:
    post:
      consumes:
      - application/json
      description: 忘记密码->修改密码
      parameters:
      - description: user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/service.UserForgetChangePassword'
      produces:
      - application/json
      responses:
        "200":
          description: '{"status": 200,"msg": "success" }'
          schema:
            $ref: '#/definitions/serializer.Response'
        "4001":
          description: code":4001,"data":null,"msg":"JSON类型不匹配"}
          schema:
            $ref: '#/definitions/serializer.Response'
        "4002":
          description: code":4002,"data":null,"msg":"参数错误"}
          schema:
            $ref: '#/definitions/serializer.Response'
        "4003":
          description: code":4003,"data":null,"msg":"Tag Error"}
          schema:
            $ref: '#/definitions/serializer.Response'
        "4006":
          description: code":4003,"data":null,"msg":"unauthrized account"}
          schema:
            $ref: '#/definitions/serializer.Response'
      summary: 忘记密码->修改密码
  /industry:
    get:
      description: 行业列表
      produces:
      - application/json
      responses:
        "200":
          description: '{"status": 200,"data":{"item":[],total:int},"msg": "success"
            }'
          schema:
            $ref: '#/definitions/serializer.Response'
      summary: 行业列表
  /login:
    post:
      consumes:
      - application/json
      description: 用户登陆
      parameters:
      - description: user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/service.UserLoginService'
      produces:
      - application/json
      responses:
        "200":
          description: '{"status": 200,"data":{"_id":000000,"token":token,"name":adeljck},"msg":
            "success" }'
          schema:
            $ref: '#/definitions/serializer.Response'
        "4001":
          description: code":4001,"data":null,"msg":"JSON类型不匹配"}
          schema:
            $ref: '#/definitions/serializer.Response'
        "4002":
          description: code":4002,"data":null,"msg":"参数错误"}
          schema:
            $ref: '#/definitions/serializer.Response'
        "4003":
          description: code":4003,"data":null,"msg":"Tag Error"}
          schema:
            $ref: '#/definitions/serializer.Response'
        "4005":
          description: code":4003,"data":null,"msg":"账号或密码错误"}
          schema:
            $ref: '#/definitions/serializer.Response'
        "4006":
          description: code":4003,"data":null,"msg":"unauthrized account"}
          schema:
            $ref: '#/definitions/serializer.Response'
      summary: 用户登陆
  /mine/changepassword:
    post:
      consumes:
      - application/json
      description: 用户修改密码
      parameters:
      - description: user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/service.UserChangePassword'
      produces:
      - application/json
      responses:
        "200":
          description: '{"status": 200,"msg": "success" }'
          schema:
            $ref: '#/definitions/serializer.Response'
        "4001":
          description: code":4001,"data":null,"msg":"JSON类型不匹配"}
          schema:
            $ref: '#/definitions/serializer.Response'
        "4002":
          description: code":4002,"data":null,"msg":"参数错误"}
          schema:
            $ref: '#/definitions/serializer.Response'
        "4003":
          description: code":4003,"data":null,"msg":"Tag Error"}
          schema:
            $ref: '#/definitions/serializer.Response'
        "4006":
          description: code":4003,"data":null,"msg":"unauthrized account"}
          schema:
            $ref: '#/definitions/serializer.Response'
      summary: 用户修改密码
  /ping:
    get:
      consumes:
      - '*/*'
      description: 服务器状态检查
      produces:
      - application/json
      responses:
        "200":
          description: '{"status": 0,"data": null,"msg": "Pong" }'
          schema:
            $ref: '#/definitions/serializer.Response'
      summary: 服务器状态检查
  /project:
    delete:
      consumes:
      - application/json
      description: 删除项目
      parameters:
      - description: project
        in: body
        name: projects
        required: true
        schema:
          $ref: '#/definitions/service.ProjectDelete'
      produces:
      - application/json
      responses:
        "200":
          description: '{"status": 200,"data":bull,"msg": "success" }'
          schema:
            $ref: '#/definitions/serializer.Response'
        "4001":
          description: code":4001,"data":null,"msg":"JSON类型不匹配"}
          schema:
            $ref: '#/definitions/serializer.Response'
        "4002":
          description: code":4002,"data":null,"msg":"参数错误"}
          schema:
            $ref: '#/definitions/serializer.Response'
        "4003":
          description: code":4003,"data":null,"msg":"failed"}
          schema:
            $ref: '#/definitions/serializer.Response'
      summary: 删除项目
    post:
      consumes:
      - application/json
      description: 添加项目
      parameters:
      - description: project
        in: body
        name: projects
        required: true
        schema:
          $ref: '#/definitions/service.ProjectAdd'
      produces:
      - application/json
      responses:
        "200":
          description: '{"status": 200,"data":bull,"msg": "success" }'
          schema:
            $ref: '#/definitions/serializer.Response'
        "4001":
          description: code":4001,"data":null,"msg":"JSON类型不匹配"}
          schema:
            $ref: '#/definitions/serializer.Response'
        "4002":
          description: code":4002,"data":null,"msg":"参数错误"}
          schema:
            $ref: '#/definitions/serializer.Response'
        "4003":
          description: code":4003,"data":null,"msg":"Tag Error"}
          schema:
            $ref: '#/definitions/serializer.Response'
      summary: 添加项目
    put:
      consumes:
      - application/json
      description: 接手项目
      parameters:
      - description: project
        in: body
        name: projects
        required: true
        schema:
          $ref: '#/definitions/service.GetProject'
      produces:
      - application/json
      responses:
        "200":
          description: '{"status": 200,"data":bull,"msg": "success" }'
          schema:
            $ref: '#/definitions/serializer.Response'
        "4001":
          description: code":4001,"data":null,"msg":"JSON类型不匹配"}
          schema:
            $ref: '#/definitions/serializer.Response'
        "4002":
          description: code":4002,"data":null,"msg":"参数错误"}
          schema:
            $ref: '#/definitions/serializer.Response'
        "4003":
          description: code":4003,"data":null,"msg":"failed"}
          schema:
            $ref: '#/definitions/serializer.Response'
      summary: 接手项目
  /project/{id}:
    get:
      consumes:
      - application/json
      description: 获取项目详细信息
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"status": 200,"data":items,"msg": "success" }'
          schema:
            $ref: '#/definitions/serializer.Response'
        "4001":
          description: code":4001,"data":null,"msg":"JSON类型不匹配"}
          schema:
            $ref: '#/definitions/serializer.Response'
        "4002":
          description: code":4002,"data":null,"msg":"参数错误"}
          schema:
            $ref: '#/definitions/serializer.Response'
        "4003":
          description: code":4003,"data":null,"msg":"failed"}
          schema:
            $ref: '#/definitions/serializer.Response'
      summary: 获取项目详细信息
  /projects/{page}:
    get:
      description: 项目列表
      parameters:
      - description: page
        in: path
        name: page
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"status": 200,"data":{"item":[],total:int},"msg": "success"
            }'
          schema:
            $ref: '#/definitions/serializer.Response'
      summary: 项目列表
  /registe:
    post:
      consumes:
      - application/json
      description: 用户注册
      parameters:
      - description: user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/service.User'
      produces:
      - application/json
      responses:
        "200":
          description: '{"status": 200,"data":null,"msg": "success" }'
          schema:
            $ref: '#/definitions/serializer.Response'
        "4001":
          description: code":4001,"data":null,"msg":"JSON类型不匹配"}
          schema:
            $ref: '#/definitions/serializer.Response'
        "4002":
          description: code":4002,"data":null,"msg":"参数错误"}
          schema:
            $ref: '#/definitions/serializer.Response'
        "4003":
          description: code":4003,"data":null,"msg":"Tag Error"}
          schema:
            $ref: '#/definitions/serializer.Response'
      summary: 用户注册
swagger: "2.0"
